version: "3.9"

services:
  app:
    build: .
    hostname: app
    command:
      - sh
      - -c
      - |
        python manage.py migrate
        python manage.py loaddata data.json
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5433
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    tty: true
  db:
    image: "postgres:14-alpine"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/data/postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 2s
      retries: 5
volumes:
  postgres_data:
