# Generated by Django 4.2.4 on 2024-03-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='co_status',
            field=models.BooleanField(db_column='co_status', default=True),
        ),
    ]
