# Generated by Django 4.2.4 on 2024-03-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='dt_limit',
            field=models.DateTimeField(blank=True, db_column='dt_limite_formulario', null=True),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
