# Generated by Django 4.2.4 on 2024-02-27 18:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerform',
            name='nco_answer_form_question',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, db_column='nco_pergunta_resposta_formulario', null=True, size=None),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='nco_form_item',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, db_column='nco_item_formulario', null=True, size=None),
        ),
        migrations.CreateModel(
            name='AnswerFormQuestion',
            fields=[
                ('dt_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('dt_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('co_answer_form_question', models.AutoField(db_column='co_pergunta_resposta_formulario', primary_key=True, serialize=False, unique=True)),
                ('nds_answer_question_item', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, db_column='ds_resposta_questao_item', null=True, size=None)),
                ('nds_answer_question_str', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, db_column='ds_resposta_questao_str', null=True, size=None)),
                ('co_answer_form', models.ForeignKey(db_column='co_resposta_formulario', on_delete=django.db.models.deletion.CASCADE, to='services.answerform')),
                ('co_form_question', models.ForeignKey(db_column='co_pergunta_formulario', on_delete=django.db.models.deletion.CASCADE, to='services.formquestion')),
            ],
            options={
                'db_table': 'tb_pergunta_resposta_formulario',
            },
        ),
    ]
