# Generated by Django 4.2.4 on 2024-03-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='co_type_question',
            field=models.TextField(db_column='ds_tipo_pergunta'),
        ),
    ]
