# Generated by Django 4.2.4 on 2024-03-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_form_dt_limit_alter_formquestion_is_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='nco_status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='ds_link',
        ),
    ]
