# Generated by Django 4.2.4 on 2024-03-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_formquestion_is_required_messageform_co_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
