# Generated by Django 4.2.4 on 2024-03-24 03:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_formquestion_co_type_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormStep',
            fields=[
                ('dt_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('dt_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('co_form_step', models.AutoField(db_column='co_etapa_formulario', primary_key=True, serialize=False, unique=True)),
                ('no_form_step', models.CharField(db_column='no_etapa_formulario', max_length=255)),
                ('ds_form_step', models.TextField(db_column='ds_etapa_formulario')),
                ('nco_form_question', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='nco_pergunta_formulario', size=None)),
            ],
            options={
                'db_table': 'tb_etapa_formulario',
            },
        ),
        migrations.RemoveField(
            model_name='form',
            name='nco_question',
        ),
        migrations.AddField(
            model_name='form',
            name='nco_step',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_column='nco_etapa_formulario', default=[], size=None),
            preserve_default=False,
        ),
    ]
