# Generated by Django 4.2.4 on 2024-03-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_tutorial_content_tutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='nco_answer',
        ),
        migrations.AlterField(
            model_name='user',
            name='co_registration',
            field=models.CharField(blank=True, db_column='co_matricula', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='ds_password',
            field=models.CharField(blank=True, db_column='ds_senha', max_length=255),
        ),
    ]
